#!/bin/bash -eux
if [[ -z $CI ]]; then
  echo 'This script is for CI only' >&2
  exit 1
fi
formula=tmstatus.sh.rb
repo_url=$(grep head $formula | cut -d\' -f2)
repo_dir=$(mktemp -d)
git clone "$repo_url" "$repo_dir"
pushd "$repo_dir"
latest=$(git tag | sort -V | tail -1 | cut -d'v' -f2)
popd
formula_version=$(grep version $formula | cut -d\' -f2)
if [[ $latest = "$formula_version" ]]; then
  echo 'Already up-to-date'
  exit 0
fi
url="https://github.com/matteocorti/tmstatus.sh/releases/download/v$latest/tmstatus.sh-$latest.tar.bz2"
sha256=$(curl -Ls "$url" | shasum -a 256 | cut -wf1)
if [[ -z $sha256 ]]; then
  echo "Failed to fetch the latest version: $latest" >&2
  exit 1
fi
perl -pe "s,(?<=url ').+(?='),$url," -i $formula
perl -pe "s,(?<=sha256 ').+(?='),$sha256," -i $formula
perl -pe "s,(?<=version ').+(?='),$latest," -i $formula
if git status -sb | grep -v '^#'; then
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git add .
  git commit -m "[ci skip] feat: update $latest"
  git remote set-url origin git@github.com:"$GITHUB_REPOSITORY"
  git push origin $GITHUB_REF_NAME
fi
